//ESTADO PARA EL CATALOGO DE VEHICULOS
export const GET_VEHICLE_SUCCESSFUL = 'GET_VEHICLE_SUCCESSFUL';


//ESTADO PARA LOS PEDIDOS
export const SELECT_VEHICLE = 'SELECT_VEHICLE';

//ESTADO PARA EL HISTORIAL DE SEVICIO
export const GET_HISTORY_SUCCESSFUL = 'GET_HISTORY_SUCCESSFUL';

//GUARDAR VEHICULO EN EL CARRITO DE COMPRAS
export const SAVE_CAR = 'SAVE_CAR'

//MOSTRAR CARRITO DE COMPRAS
export const SHOW_CARSHOP = 'SHOW_CARSHOP'

//ELIMINAR VEHICULO DEL CARRITO DE COMPRAS
export const DELETE_VEHICLE_SHOP = 'DELETE_VEHICLE_SHOP' 

//LIMPIAR CARRRILO DE COMPRAS
export const CLEAR_SHOP = 'CLEAR_SHOP'

